app/forms/manage.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, RadioField, IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, URL, NumberRange
from app import app


class AddForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    url = StringField('URL', validators=[DataRequired(), URL()])
    ua = StringField('User Agent')
    referer = StringField('Referer')
    cookie = StringField('Cookie')
    method = SelectField('Method', choices=[('GET', 'GET'), ('POST', 'POST')])
    postdata = StringField('Post Data(json)')
    if app.config['FREQ_SECOND']:
        unit = '(seconds)'
    else:
        unit = '(minutes)'
    freq = IntegerField('Frequency' + unit, validators=[DataRequired(), NumberRange(1, 100000)])
    watch_type = SelectField('Send mail when',
                            choices=[('change', 'Page changes'), ('keyword', 'Keyword detected')])
    keyword = StringField('Keyword')
    notify_content = SelectField('Mail content',
                                choices=[('diff', 'Insertions and deletions (Diff)'), ('new', 'New content'),
                                         ('all', 'Entire new page')])
    submit_btn = SubmitField('Submit')

app/views/manage.py
from flask import Blueprint, render_template, redirect, url_for, request, Response
from flask_login import current_user, login_required
from app.forms import *
from app.models import *
from app.mail import *
from app import app
from app.download import *
from datetime import datetime

manage = Blueprint('manage', __name__)


@manage.route('/')
@login_required
def index():
    pages = current_user.pages
    if app.config['FREQ_SECOND']:
        unit = 'sec'
    else:
        unit = 'min'
    return render_template('manage.html', user=current_user, pages=pages, now=datetime.now(), unit=unit)


@manage.route('/add/', methods=['POST', 'GET'])
@login_required
def add():
    form = AddForm(request.form, Page('','','','','','','GET','change','','diff',10,None))
    if request.method == 'POST':
        if form.validate_on_submit():
            page = Page(form['name'].data,
                        form['url'].data,
                        form['postdata'].data,
                        form['ua'].data,
                        form['referer'].data,
                        form['cookie'].data,
                        form['method'].data,
                        form['watch_type'].data,
                        form['keyword'].data,
                        form['notify_content'].data,
                        form['freq'].data,
                        current_user
                        )
            page.save()
            return redirect(url_for('manage.index'))
    return render_template('add.html', form=form)


@manage.route('/delete/<int:id>')
@login_required
def delete(id):
    page = Page.query.get(id)
    if not page or page.user != current_user:
        return redirect(url_for('manage.index'))
    page.delete()
    return redirect(url_for('manage.index'))


@manage.route('/edit/<int:id>', methods=['POST', 'GET'])
@login_required
def edit(id):
    page = Page.query.get(id)
    if not page or page.user != current_user:
        return redirect(url_for('manage.index'))
    form = AddForm(request.form, page)
    if request.method == 'POST':
        if form.validate_on_submit():
            page.name = form['name'].data
            page.url = form['url'].data
            page.postdata = form['postdata'].data
            page.ua = form['ua'].data
            page.referer = form['referer'].data
            page.cookie = form['cookie'].data
            page.method = form['method'].data
            page.watch_type = form['watch_type'].data
            page.keyword = form['keyword'].data
            page.notify_content = form['notify_content'].data
            page.freq = form['freq'].data
            page.save()
            return redirect(url_for('manage.index'))
    return render_template('edit.html', form=form, id=page.id)


@manage.route('/test/<int:id>', methods=['POST', 'GET'])
@login_required
def test(id):
    page = Page.query.get(id)
    if not page or page.user != current_user:
        return redirect(url_for('manage.index'))
    try:
        text = download(page.url, page.ua, page.referer, page.cookie, page.method, page.postdata)
    except Exception as e:
        text = type(e).__name__
    return render_template('test.html', text=text)

app/views/user.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, current_user, login_required, logout_user
from app.forms import *
from app.models import *
from random import randint
from app import db
from app.mail import *

user = Blueprint('user', __name__)


@user.route('/login/', methods=['POST', 'GET'])
def login():
    next_url = request.args.get('next') or url_for('home.index')
    if current_user.is_authenticated:
        return redirect(next_url)
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user, status = User.auth(form['email'].data, form['password'].data)
            if status:
                login_user(user)
                return redirect(next_url)
            else:
                flash('email or password incorrect', 'error')
        else:
            flash('please input email and password', 'error')
    return render_template('login.html', form=form)


@user.route('/register/', methods=['POST', 'GET'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if User.exist_user(form['email'].data):
                flash('user already exists', 'error')
            else:
                user = User.get_user_from_email(form['email'].data)
                if not user:
                    user = User(form['email'].data, form['password'].data)
                code = str(randint(100000, 999999))
                user.reg_token = code
                user.save()
                send_mail('Confirm code', code, form['email'].data)
                return redirect(url_for('user.confirm'))
        else:
            flash('email not valid or password not match', 'error')
    return render_template('register.html', form=form)


@user.route('/confirm/', methods=['POST', 'GET'])
def confirm():
    form = ConfirmForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.get_confirm_user(form['code'].data)
            if user:
                user.active = True
                user.save()
                login_user(user)
                return redirect(url_for('home.index'))
            else:
                flash('wrong code', 'error')
        else:
            flash('please input confirm code', 'error')
    return render_template('confirm.html', form=form)


@user.route('/logout/')
def logout():
    logout_user();
    return redirect(url_for('home.index'));

app/templates/add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}New subscription{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
  <h1>{{ self.title() }}</h1>

  <div>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/fixes.html" as fixes %}

{% block head %}
{{super()}}
{{fixes.ie8()}}
{% endblock %}

app/templates/confirm.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}Confirm{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
  <h1>{{ self.title() }}</h1>

  <div>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/edit.html
{% from "_form.html" import render_field %}
{% extends "layout.html" %}
{% block content %}
    <h3>Edit subscription</h3>
    <form method='post' action={{ url_for('manage.edit',id=id) }}>
        <dl>
            {{ form.csrf_token }}
            {{ render_field(form.name) }}
            {{ render_field(form.url) }}
            {{ render_field(form.ua) }}
            {{ render_field(form.referer) }}
            {{ render_field(form.cookie) }}
            {{ render_field(form.method) }}
            {{ render_field(form.postdata) }}
            {{ render_field(form.freq) }}
            {{ render_field(form.watch_type) }}
            {{ render_field(form.notify_content) }}
        </dl>
        <button type='submit'>Submit</button>
    </form>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}Subscribe to Anything Login{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
  <h1>{{ self.title() }}</h1>

  <div>
    {{ wtf.quick_form(form) }}
  </div>
  <h4>
    <p></p>
    <p>
      <a href={{ url_for('user.register') }}>Register new user</a>
    </p>
  </h4>
</div>
{% endblock %}

app/templates/manage.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}Manage your subscriptions{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
    <h1>{{ self.title() }}</h1>
    Current user: <code>{{ user.email }}</code> <a class="btn btn-sm btn-default" type="button" href={{ url_for('user.logout') }}>Log out</a><br><br>
    <a class="btn btn-default" type="button" href={{ url_for('manage.add') }}>New subscription</a><br>
    <h4>Current subscriptions({{ pages|length }}):</h4>
    <table class="table">
    <tr>
        <th>Name</th>
        <th>URL</th>
        <th>Frequency({{ unit }})</th>
        <th>Last check</th>
        <th>Last status</th>
        <th>Test</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    {% for p in pages %}
    <tr>
        <td>{{ p.name }}</td>
        <td>{{ p.url }}</td>
        <td>{{ p.freq}}</td>
        <td>{{ p.last_check }}</td>
        <td>{{ p.last_status }}</td>
        <td><a class="btn btn-sm btn-info" type="button" href={{ url_for('manage.test',id=p.id) }}>Test</a></td>
        <td><a class="btn btn-sm btn-warning" type="button" href={{ url_for('manage.edit',id=p.id) }}>Edit</a></td>
        <td><a class="btn btn-sm btn-danger" type="button" href={{ url_for('manage.delete',id=p.id) }}>Delete</a></td>
    </tr>
    {% endfor %}
    </table>
    Server time: {{ now }}
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}Register New User{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
  <h1>{{ self.title() }}</h1>

  <div>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/test.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as util %}

{% block title %}Test Result{% endblock %}

{% block content %}
{{util.flashed_messages(dismissible=True)}}
<div class="container">
  <h1>{{ self.title() }}</h1>

  <pre>{{ text }}</pre>
</div>
{% endblock %}